version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.0.0
executors:
  docker-host:
    environment:
      IMAGE: smartbear/git-en-boite
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  test-in-node:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd packages/la-boite && yarn
            - run: cd packages/la-boite && ./node_modules/.bin/tsc
            - run: cd packages/la-boite && yarn run lint
            - run: cd packages/la-boite && yarn test

  build-container:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: smartbear/git-en-boite
          path: packages/la-boite
      - run: 
          name: Run tests in container
          command: docker run -ti smartbear/git-en-boite:latest yarn test

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - test-in-node
      - build-container
