version: 2.1

orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.0.0

jobs:
  test-in-node:
    docker:
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: git-en-boite-test
    executor:
      name: node/default
    steps:
      - checkout
      - run: whoami
      - run: apt install -y postgresql-client
      - node/with-cache:
          dir: ~/project/packages/la-boite/node_modules
          steps:
            - run: cd packages/la-boite && yarn
            - run: cd packages/la-boite && ./node_modules/.bin/tsc
            - run: cd packages/la-boite && yarn run lint
            - run: 
                name: Run tests
                command: cd packages/la-boite && yarn test
                environment:
                  GIT_EN_BOITE_PG_URL: postgres://root@localhost/git-en-boite-test

workflows:
  version: 2.1
  build:
    jobs:
      - test-in-node
      - docker/publish:
          image: smartbear/git-en-boite
          path: packages/la-boite
          tag: latest
          after_build:
            - run: 
                name: Run tests in container
                command: docker run -ti smartbear/git-en-boite:latest yarn test
          filters:
            branches:
              only: master
