version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
  docker-host:
    environment:
      IMAGE: smartbear/git-en-boite
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  test-in-node:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd packages/la-boite && yarn
            - run: cd packages/la-boite && ./node_modules/.bin/tsc
            - run: cd packages/la-boite && yarn run lint
            - run: cd packages/la-boite && yarn test

  build-container:
    executor: docker-host
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE:latest packages/la-boite
      - run: 
          name: Run tests in container
          command: docker run -ti $IMAGE:latest yarn test
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  test-in-container:
    executor: docker-host
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run: docker run -ti $IMAGE:latest yarn test

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - test-in-node
      - build-container
      - test-in-container:
          requires:
            - build-container
