version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t smartbear/git-en-boite:latest packages/la-boite
  test:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run: docker run -ti smartbear/git-en-boite:latest yarn lint # TODO: move this into Dockerfile
      - run: docker run -ti smartbear/git-en-boite:latest yarn test

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
