version: 2.1

orbs:
  node: circleci/node@2.0.0
  docker: circleci/docker@1.0.0

jobs:
  test-in-node:
    docker:
      - image: circleci/node:current
        environment:
          GIT_EN_BOITE_PG_URL: postgres://root@localhost/git-en-boite-test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: git-en-boite-test
    steps:
      - checkout
      - run: apt install -y postgresql-client
      - node/install-packages:
          app-dir: packages/la-boite
          pkg-manager: yarn
          with-cache: true
      - run: cd packages/la-boite && ./node_modules/.bin/tsc
      - run: cd packages/la-boite && yarn run lint
      - run: cd packages/la-boite && yarn test

workflows:
  version: 2.1
  build:
    jobs:
      - test-in-node
      - docker/publish:
          image: smartbear/git-en-boite
          path: packages/la-boite
          tag: latest
          after_build:
            - run: 
                name: Run tests in container
                command: docker run -ti smartbear/git-en-boite:latest yarn test
          filters:
            branches:
              only: master
