version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - cd packages/la-boite
            - run: npm install
            - run: ./node_modules/.bin/tsc
            - run: npm run lint
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
